language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - nvm install-latest-npm
install:
  - npm i -g codecov
  - npm i
script:
  - npm test
  - codecov
after_success:
  - npm run test:coverage